/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import java.util.Arrays;

/**
 * Running Sum of 1d Array.
 */
public final class Solution {
    /**
     * @param nums The input array of integers to be added together.
     * @return nums The output array of running sum of integers.
     * @time Time complexity is O(N).
     * @space Space complexity is O(1).
     */
    public int[] runningSum(int[] nums) {
        for (int i = 1; i < nums.length; i++) {
            nums[i] = nums[i - 1] + nums[i];
        }
        return nums;
    }

    /**
     * @param args User input array of integers.
     */
    public static void main(String[] args) {
        Solution s = new Solution();
        int[] input = {1,2,3,4,5};
        
        if (args.length > 0) {
            input = new int[args.length];
            for (int i = 0; i < args.length; i++)
                input[i] = Integer.parseInt(args[i]);
        }
        System.out.println("Input: " + Arrays.toString(input));
        System.out.println("Output: " + Arrays.toString(s.runningSum(input)));
    }
}
